title:        Born Neet
tagline:      Born Neet
url:          http://www.bornneet.com
author:
  name:       "Tatsuya Tobioka"
  email:      ""
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
